ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE client MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE team MODIFY COLUMN manager_id BIGINT NOT NULL;
ALTER TABLE team MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE ticket MODIFY COLUMN client_id BIGINT NOT NULL;
ALTER TABLE ticket MODIFY COLUMN team_id BIGINT;