ALTER TABLE users
    modify COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE client
    modify COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE ticket
    modify COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE team
    modify COLUMN id BIGINT NOT NULL AUTO_INCREMENT;